#!/bin/zsh

## . INCLUDES ##
## END INCLUDES ##

## FUNCTIONS ##

usage(){
    printf "\n\tThe purpose of this script is to address audio issues with sleep/suspend in MacOS Monterey \n\n"
    printf "\nUsage: rsaudio [-c|a] "
    printf "\n\t-c: restart only Google Chrome "
    printf "\n\t-a: restart only coreaudiod "
    printf "\nNo argument: restart coreaudiod (will prompt for sudo password) "
    printf "\nthen prompt to restart Google Chrome \n"
    printf "\n\n\t## This is still a WIP ## \n\n"
}

restart_audio(){
    printf "Kill coreaudiod \n"
    sudo killall coreaudiod
    printf "done \n"
}

restart_chrome(){
    printf "\nKill Google Chrome \n"
    sudo killall Google\ Chrome
    printf "done \n"

    printf "\nRestart Google Chrome \n"
    #open -a Google\ Chrome
    open -a "Google Chrome"
    printf "done \n"
}

no_flags(){
    restart_audio
    printf "Restart Google Chrome? "
        read ChRestart
        case $ChRestart in
            [yY]*) restart_chrome ;;
            *    ) exit 0 ;;
        esac
}

## END FUNCTIONS

## MAIN ## 

if [ -z "$1" ]; then
    no_flags
    else 
        case "$1" in
            -a) restart_audio ; exit 0  ;;
            -c) restart_chrome ; exit 0 ;;
            -h) usage ; exit 0          ;;
            * ) usage ; exit 1          ;;
        esac
fi

printf "\n"
exit 0

## END MAIN ## 

## NOTES / ADDENDA / VERSION ##
## END NOTES / ADDENDA / VERSION ##
